name: smart_waste_app
description: Smart waste sorting via image and speech.
version: 1.0.0+1


environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.1
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.5
  http: ^1.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

